import os
from datetime import datetime

class KUKATranslator:
    """
    Translates a trajectory into KUKA KRL using Inline Forms (ILF).
    This matches the standard KUKA SmartPad UI format, allowing for "Touch Up".
    """
    def __init__(self, program_name="layer_test", routine_name="Routine2", tool_id=2, base_id=10):
        self.program_name = program_name
        self.routine_name = routine_name
        self.tool_id = tool_id
        self.base_id = base_id
        self.default_vel = 0.5 # m/s

    def _generate_dat_point(self, point_idx, pose):
        """Generates the memory variables for a single point in the .dat file."""
        p_name = f"P{point_idx}"
        return f""";
DECL LDAT LCPDAT{p_name}={{VEL {pose['VEL']/1000.0},ACC 100,APO_DIST 5,APO_FAC 50.0,ORI_TYP #VAR,CIRC_TYP #BASE,JERK_FAC 50.0}}
DECL FDAT F{p_name}={{TOOL_NO {self.tool_id},BASE_NO {self.base_id},IPO_FRAME #BASE,POINT2[] " ",TQ_STATE FALSE}}
DECL E6POS X{p_name}={{X {pose['X']:.3f},Y {pose['Y']:.3f},Z {pose['Z']:.3f},A {pose['A']:.3f},B {pose['B']:.3f},C {pose['C']:.3f},S 7,T 51,E1 0,E2 0,E3 0,E4 0,E5 0,E6 0}}
"""

    def _generate_ilf_lin(self, point_idx, velocity):
        """Generates the Inline Form (ILF) for a LIN movement in the .src file."""
        p_name = f"P{point_idx}"
        return f""";FOLD LIN {p_name} CONT Vel= {velocity/1000.0} m/s CPDAT{p_name} Tool[{self.tool_id}] Base[{self.base_id}]   ;%{{PE}}
;FOLD Parameters ;%{{h}}
;Params IlfProvider=kukaroboter.basistech.inlineforms.movement.old; Kuka.IsGlobalPoint=False; Kuka.PointName={p_name}; Kuka.BlendingEnabled=True; Kuka.MoveDataName=CPDAT{p_name}; Kuka.VelocityPath={velocity/1000.0}; Kuka.CurrentCDSetIndex=0; Kuka.MovementParameterFieldEnabled=True; IlfCommand=LIN
;ENDFOLD
$BWDSTART = FALSE
LDAT_ACT=LCPDAT{p_name}
FDAT_ACT=F{p_name}
BAS (#CP_PARAMS,{velocity/1000.0})
SET_CD_PARAMS (0)
LIN  X{p_name} C_DIS
;ENDFOLD
"""

    def _generate_ilf_wait(self, wait_time):
        """Generates the Inline Form (ILF) for a WAIT SEC command."""
        return f""";FOLD WAIT Time={wait_time} sec;%{{PE}}%R 8.5.16,%MKUKATPBASIS,%CWAIT,%VWAIT,%P 3:{wait_time}
WAIT SEC {wait_time}
;ENDFOLD
"""

    def _write_dat_file(self, trajectory, output_dir):
        file_path = os.path.join(output_dir, f"{self.program_name}.dat")
        
        dat_header = f"""&ACCESS RVP
&PARAM EDITMASK = *
DEFDAT  {self.program_name}
;FOLD EXTERNAL DECLARATIONS;%{{PE}}%MKUKATPBASIS,%CEXT,%VCOMMON,%P
;FOLD BASISTECH EXT;%{{PE}}%MKUKATPBASIS,%CEXT,%VEXT,%P
EXT  BAS (BAS_COMMAND  :IN,REAL  :IN )
DECL INT SUCCESS
;ENDFOLD (BASISTECH EXT)
;FOLD USER EXT;%{{E}}%MKUKATPUSER,%CEXT,%VEXT,%P
;Make your modifications here

;ENDFOLD (USER EXT)
;ENDFOLD (EXTERNAL DECLARATIONS)

INT APP_GENNUMBER = 215375
INT APP_ANSWER
INT APP_OFFSET
DECL STATE_T APP_STATE

; Data for {self.routine_name}
"""
        with open(file_path, 'w') as f:
            f.write(dat_header)
            # Write every point's variable declaration
            for i, waypoint in enumerate(trajectory, start=1):
                f.write(self._generate_dat_point(i, waypoint))
                
            f.write(f";ENDDAT for {self.routine_name}\n\nENDDAT\n")
        print(f"Success: .dat file generated at -> {file_path}")

    def _write_src_file(self, trajectory, output_dir):
        file_path = os.path.join(output_dir, f"{self.program_name}.src")
        timestamp = datetime.now().strftime("%Y-%m-%d-%H_%M")
        
        # Mirroring the exact structure provided: INI, CHECK, JobInfo, HomePos
        src_header = f"""DEF  {self.program_name} ( )

;FOLD INI
CONTINUE
IF NOT $ON_PATH THEN
  ;FOLD BASISTECH INI
    GLOBAL INTERRUPT DECL 3 WHEN $STOPMESS==TRUE DO IR_STOPM ( )
    INTERRUPT ON 3 
    BAS (#INITMOV,0 )
  ;ENDFOLD (BASISTECH INI)
  ;FOLD USER INI
    ;Make your modifications here

  ;ENDFOLD (USER INI)
ENDIF
;ENDFOLD (INI)

;FOLD CHECK DAT-FILE GENERATION NUMBER
  IF APP_GENNUMBER <> 215375 THEN
    LOOP
      MsgQuit("InconsistenceSRCandDAT",,,,1)
      HALT
    ENDLOOP
  ENDIF
;ENDFOLD

;fold Jobinfo
;Job information: {self.program_name}
;Product : 3.1.0.28784
;Date: {timestamp}
;Project name: {self.program_name}
;Author: Alhadi Zidan
;Company: CRITT-TJFU
;Division: CSAMProj
;Comment: Autogenerated CSAM Path
;endfold

; --- GLOBAL BLENDING OVERRIDES ---
$APO.CDIS = 1.0  ; Distance blending radius (mm)
$APO.CVEL = 100  ; Velocity blending (%)
$APO.CORI = 5.0  ; Orientation blending (degrees)
$ADVANCE = 5
;fold HomePositions
;XHOME5={{A1 -1120,A2 -102,A3 90,A4 0,A5 -70,A6 0,E1 0,E2 0,E3 0,E4 0,E5 0,E6 0}}
;$AXIS_HOME[5]=XHOME5
;endfold

;FOLD PTP HOME5  Vel=100 % DEFAULT;%{{PE}}
;FOLD Parameters ;%{{h}}
;Params IlfProvider=kukaroboter.basistech.inlineforms.movement.old; Kuka.IsGlobalPoint=False; Kuka.PointName=HOME5; Kuka.BlendingEnabled=False; Kuka.MoveDataPtpName=DEFAULT; Kuka.VelocityPtp=100; Kuka.CurrentCDSetIndex=0; Kuka.MovementParameterFieldEnabled=True; IlfCommand=PTP
;ENDFOLD
$BWDSTART = FALSE
PDAT_ACT=PDEFAULT
FDAT_ACT=FDEFAULT
BAS (#PTP_PARAMS,100)
SET_CD_PARAMS (0)
$H_POS=XHOME
PTP XHOME5 
;ENDFOLD

{self.routine_name}()
WAIT SEC 0.3
;FOLD PTP HOME5  Vel=100 % DEFAULT;%{{PE}}
;FOLD Parameters ;%{{h}}
;Params IlfProvider=kukaroboter.basistech.inlineforms.movement.old; Kuka.IsGlobalPoint=False; Kuka.PointName=HOME5; Kuka.BlendingEnabled=False; Kuka.MoveDataPtpName=DEFAULT; Kuka.VelocityPtp=100; Kuka.CurrentCDSetIndex=0; Kuka.MovementParameterFieldEnabled=True; IlfCommand=PTP
;ENDFOLD
$BWDSTART = FALSE
PDAT_ACT=PDEFAULT
FDAT_ACT=FDEFAULT
BAS (#PTP_PARAMS,100)
SET_CD_PARAMS (0)
$H_POS=XHOME
PTP XHOME5 
;ENDFOLD
END

DEF {self.routine_name}()
BOOL SeperateFiles
SeperateFiles = FALSE

"""
        with open(file_path, 'w') as f:
            f.write(src_header)
            
            # Write the ILF blocks for every point
            for i, waypoint in enumerate(trajectory, start=1):
                vel = waypoint.get('VEL', self.default_vel)
                f.write(self._generate_ilf_lin(i, vel))
                
                # Check if this waypoint has a pause/wait command
                if 'wait' in waypoint and waypoint['wait'] is not None:
                    f.write(self._generate_ilf_wait(waypoint['wait']))
                    
            f.write("\nEND\n")
            
        print(f"Success: .src file generated at -> {file_path}")

    def generate_programs(self, trajectory, output_dir="."):
        os.makedirs(output_dir, exist_ok=True)
        self._write_dat_file(trajectory, output_dir)
        self._write_src_file(trajectory, output_dir)